dist: trusty
sudo: required

language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get install -qq bwa
    - wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
    - bzip2 -d samtools-1.3.1.tar.bz2
    - tar -xf samtools-1.3.1.tar
    - cd samtools-1.3.1
    - sudo ./configure
    - sudo make
    - sudo make install
    - cd ..

install: "pip install -r requirements.txt"

script: "python Dellingr/DellingrPipeline.py -c etc/dellingr_config.ini"
script: "python Dellingr/DellingrPipeline.py -c etc/dellingr_config.ini -j 2 --directory_name Multithread --bwa $(which bwa) --samtools $(which samtools)"
